#!/usr/sbin/nft -f
# /etc/nftables.conf  —  GW-MAIN
# enp0s3=WAN-A | enp0s8=WAN-B | enp0s9=LAN | enp0s10=DMZ | tun0=nomades | tun1=site-à-site
flush ruleset

define WANS = { "enp0s3", "enp0s8" }

table inet fw {
  chain input {
    type filter hook input priority 0; policy drop;
    ct state established,related accept
    iifname "lo" accept
    iifname "enp0s9" accept                      # admin depuis le LAN
    iifname { "tun0", "tun1" } accept
    iifname $WANS udp dport { 1194, 1195 } accept # OpenVPN sur les deux fibres
    ip protocol icmp accept
  }

  chain forward {
    type filter hook forward priority 0; policy drop;
    ct state established,related accept
    iifname { "tun0", "tun1" } accept            # tunnels
    oifname { "tun0", "tun1" } accept
    iifname "enp0s9" oifname $WANS accept         # LAN -> Internet
    # Publication : WAN -> DMZ (web 80/443 ; SFTP EDI 22 filtré par IP en nat)
    iifname $WANS oifname "enp0s10" tcp dport { 80, 443, 22 } accept
    iifname "enp0s10" oifname $WANS accept        # DMZ -> Internet (maj)
    # Cloisonnement : la DMZ ne peut PAS initier vers le LAN
    iifname "enp0s10" oifname "enp0s9" drop
    iifname "enp0s9" oifname "enp0s10" accept     # LAN -> DMZ (connecteur EDI, admin)
  }

  chain output { type filter hook output priority 0; policy accept; }
}

table ip nat {
  chain prerouting {
    type nat hook prerouting priority -100; policy accept;
    # Site vitrine
    iifname $WANS tcp dport { 80, 443 } dnat to 172.16.10.10
    # EDI SFTP : restreint aux IP du partenaire logistique
    iifname $WANS ip saddr { 203.0.113.200, 203.0.113.201 } tcp dport 22 dnat to 172.16.10.20
  }
  chain postrouting {
    type nat hook postrouting priority 100; policy accept;
    # NAT Internet (sur le WAN actif), PAS pour l'inter-sites (10.0.0.0/8)
    ip saddr 10.10.0.0/24   ip daddr != 10.0.0.0/8 oifname $WANS masquerade
    ip saddr 172.16.10.0/24 ip daddr != 10.0.0.0/8 oifname $WANS masquerade
  }
}
