# Extrait /etc/ssh/sshd_config  —  SRV-EDI (DMZ) : SFTP chrooté pour partenaires
Subsystem sftp internal-sftp

Match Group sftp-edi
    ChrootDirectory /srv/edi/%u
    ForceCommand internal-sftp
    AllowTcpForwarding no
    X11Forwarding no
    PermitTunnel no
    PermitTTY no
    AuthenticationMethods publickey
    PasswordAuthentication no
