# /etc/openvpn/server/roadwarrior.conf  —  GW-MAIN (accès nomades)
port 1194
proto udp
dev tun

ca       ca.crt
cert     gw-main.crt
key      gw-main.key
dh       dh.pem
tls-auth ta.key 0

topology subnet
server 10.8.0.0 255.255.255.0

# Accès au LAN (SMB + ERP) + DNS interne
push "route 10.10.0.0 255.255.255.0"
push "dhcp-option DNS 10.10.0.10"
push "dhcp-option DOMAIN airsolid.lan"

# Split-tunnel (pas de redirect-gateway)
keepalive 10 120
persist-key
persist-tun
cipher AES-256-GCM
auth SHA256
tls-version-min 1.2
remote-cert-tls client
# crl-verify crl.pem      # à activer après première révocation
user nobody
group nogroup
status /var/log/openvpn/rw-status.log
verb 3
